Shader "Hidden/LightweightPipeline/CopyDepth" {
	Properties {
	}
	SubShader {
		Tags { "RenderPipeline" = "LightweightPipeline" "RenderType" = "Opaque" }
		Pass {
			Name "Default"
			Tags { "RenderPipeline" = "LightweightPipeline" "RenderType" = "Opaque" }
			ColorMask 0 -1
			ZTest Always
			GpuProgramID 4809
			Program "vp" {
				SubProgram "d3d11 " {
					Keywords { "_DEPTH_NO_MSAA" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[23], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[20].xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[21].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb1[22].xyzw, r0.wwww, r1.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_DEPTH_MSAA_2" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[23], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[20].xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[21].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb1[22].xyzw, r0.wwww, r1.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_DEPTH_MSAA_4" }
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[23], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[20].xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[21].xyzw, r0.zzzz, r1.xyzw
					mad o0.xyzw, cb1[22].xyzw, r0.wwww, r1.xyzw
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					Keywords { "_DEPTH_NO_MSAA" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Depth                 0    N/A   oDepth    DEPTH   float    YES
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output oDepth
					dcl_temps 1
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					mov oDepth, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_DEPTH_MSAA_2" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Depth                 0    N/A   oDepth    DEPTH   float    YES
					//
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_resource_texture2dms(2) (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output oDepth
					dcl_temps 2
					mul r0.xy, v1.xyxx, cb0[0].zwzz
					ftoi r0.xy, r0.xyxx
					mov r0.zw, l(0,0,0,0)
					ldms r1.xyzw, r0.xyww, t0.xyzw, l(0)
					ldms r0.xyzw, r0.xyzw, t0.xyzw, l(1)
					min r0.y, r1.x, l(1.000000)
					min oDepth, r0.y, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
				SubProgram "d3d11 " {
					Keywords { "_DEPTH_MSAA_4" }
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Depth                 0    N/A   oDepth    DEPTH   float    YES
					//
					ps_4_0
					dcl_constantbuffer CB0[1], immediateIndexed
					dcl_resource_texture2dms(4) (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_output oDepth
					dcl_temps 3
					mul r0.xy, v1.xyxx, cb0[0].zwzz
					ftoi r0.xy, r0.xyxx
					mov r0.zw, l(0,0,0,0)
					ldms r1.xyzw, r0.xyww, t0.xyzw, l(0)
					min r1.x, r1.x, l(1.000000)
					ldms r2.xyzw, r0.xyww, t0.xyzw, l(1)
					min r1.x, r1.x, r2.x
					ldms r2.xyzw, r0.xyww, t0.xyzw, l(2)
					ldms r0.xyzw, r0.xyzw, t0.xyzw, l(3)
					min r0.y, r1.x, r2.x
					min oDepth, r0.y, r0.x
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}