Shader "Hidden/LightweightPipeline/ScreenSpaceShadows" {
	Properties {
	}
	SubShader {
		Tags { "IGNOREPROJECTOR" = "true" "RenderPipeline" = "LightweightPipeline" }
		Pass {
			Name "Default"
			Tags { "IGNOREPROJECTOR" = "true" "RenderPipeline" = "LightweightPipeline" }
			ZTest Always
			ZWrite Off
			Cull Off
			GpuProgramID 956
			Program "vp" {
				SubProgram "d3d11 " {
					"!!vs_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[23], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[20].xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[21].xyzw, r0.zzzz, r1.xyzw
					mad r0.xyzw, cb1[22].xyzw, r0.wwww, r1.xyzw
					mov o0.xyzw, r0.xyzw
					mul r0.xyz, r0.xywx, l(0.500000, 0.500000, 0.500000, 0.000000)
					add o1.zw, r0.zzzz, r0.xxxy
					mov o1.xy, v1.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!ps_4_0
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[22], immediateIndexed
					dcl_constantbuffer CB1[30], dynamicIndexed
					dcl_sampler s0, mode_comparison
					dcl_sampler s1, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_resource_texture2d (float,float,float,float) t1
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					dcl_temps 3
					sample r0.xyzw, v1.xyxx, t1.xyzw, s1
					add r0.x, -r0.x, l(1.000000)
					mad r0.x, r0.x, l(2.000000), l(-1.000000)
					mad r0.yz, v1.zzwz, l(0.000000, 2.000000, 2.000000, 0.000000), l(0.000000, -1.000000, -1.000000, 0.000000)
					mul r1.xyzw, -r0.zzzz, cb0[11].xyzw
					mad r1.xyzw, cb0[10].xyzw, r0.yyyy, r1.xyzw
					mad r0.xyzw, cb0[12].xyzw, r0.xxxx, r1.xyzw
					add r0.xyzw, r0.xyzw, cb0[13].xyzw
					mul r0.xyz, r0.xyzx, l(1.000000, 1.000000, -1.000000, 0.000000)
					div r0.xyz, r0.xyzx, r0.wwww
					mul r1.xyz, r0.yyyy, cb0[19].xyzx
					mad r0.xyw, cb0[18].xyxz, r0.xxxx, r1.xyxz
					mad r0.xyz, cb0[20].xyzx, r0.zzzz, r0.xywx
					add r0.xyz, r0.xyzx, cb0[21].xyzx
					add r1.xyz, r0.xyzx, -cb1[20].xyzx
					dp3 r1.x, r1.xyzx, r1.xyzx
					add r2.xyz, r0.xyzx, -cb1[21].xyzx
					dp3 r1.y, r2.xyzx, r2.xyzx
					add r2.xyz, r0.xyzx, -cb1[22].xyzx
					dp3 r1.z, r2.xyzx, r2.xyzx
					add r2.xyz, r0.xyzx, -cb1[23].xyzx
					dp3 r1.w, r2.xyzx, r2.xyzx
					lt r1.xyzw, r1.xyzw, cb1[24].xyzw
					movc r2.xyz, r1.xyzx, l(-1.000000,-1.000000,-1.000000,0), l(-0.000000,-0.000000,-0.000000,0)
					and r1.xyzw, r1.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
					add r2.xyz, r2.xyzx, r1.yzwy
					max r1.yzw, r2.xxyz, l(0.000000, 0.000000, 0.000000, 0.000000)
					dp4 r0.w, r1.xyzw, l(4.000000, 3.000000, 2.000000, 1.000000)
					add r0.w, -r0.w, l(4.000000)
					ftou r0.w, r0.w
					ishl r0.w, r0.w, l(2)
					mul r1.xyz, r0.yyyy, cb1[r0.w + 1].xyzx
					mad r1.xyz, cb1[r0.w + 0].xyzx, r0.xxxx, r1.xyzx
					mad r0.xyz, cb1[r0.w + 2].xyzx, r0.zzzz, r1.xyzx
					add r0.xyz, r0.xyzx, cb1[r0.w + 3].xyzx
					sample_c_lz r0.x, r0.xyxx, t0.xxxx, s0, r0.z
					ge r0.y, l(0.000000), r0.z
					add r0.z, -cb1[29].x, l(1.000000)
					mad r0.x, r0.x, cb1[29].x, r0.z
					movc o0.xyzw, r0.yyyy, l(1.000000,1.000000,1.000000,1.000000), r0.xxxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}