using UnityEngine;
using UnityEngine.UI;
using TMPro;

public class GameControllerScript : MonoBehaviour
{
	public CursorControllerScript cursorController;
	public PlayerScript player;
	public Transform playerTransform;
	public Transform cameraTransform;
	public Camera camera;
	public EntranceScript entrance_0;
	public EntranceScript entrance_1;
	public EntranceScript entrance_2;
	public EntranceScript entrance_3;
	public GameObject baldiTutor;
	public GameObject baldi;
	public BaldiScript baldiScrpt;
	public AudioClip aud_Prize;
	public AudioClip aud_PrizeMobile;
	public AudioClip aud_AllNotebooks;
	public GameObject principal;
	public GameObject crafters;
	public GameObject playtime;
	public PlaytimeScript playtimeScript;
	public GameObject gottaSweep;
	public GameObject bully;
	public GameObject firstPrize;
	public FirstPrizeScript firstPrizeScript;
	public GameObject quarter;
	public AudioSource tutorBaldi;
	public RectTransform boots;
	public string mode;
	public int notebooks;
	public GameObject[] notebookPickups;
	public int failedNotebooks;
	public bool spoopMode;
	public bool finaleMode;
	public bool debugMode;
	public bool mouseLocked;
	public int exitsReached;
	public int itemSelected;
	public int[] item;
	public RawImage[] itemSlot;
	public TMP_Text itemText;
	public Object[] items;
	public Texture[] itemTextures;
	public GameObject bsodaSpray;
	public GameObject alarmClock;
	public TMP_Text notebookCount;
	public GameObject pauseMenu;
	public GameObject highScoreText;
	public GameObject warning;
	public GameObject reticle;
	public RectTransform itemSelect;
	public AudioClip aud_Soda;
	public AudioClip aud_Spray;
	public AudioClip aud_buzz;
	public AudioClip aud_Hang;
	public AudioClip aud_MachineQuiet;
	public AudioClip aud_MachineStart;
	public AudioClip aud_MachineRev;
	public AudioClip aud_MachineLoop;
	public AudioClip aud_Switch;
	public AudioSource schoolMusic;
	public AudioSource learnMusic;
}
